
- name: Backup and use minimal semgrep config (temporary)
  shell: bash
  run: |
    set -e
    # 백업
    if [ -f ".semgrep/.semgrep.yml" ]; then
      cp .semgrep/.semgrep.yml .semgrep/.semgrep.yml.bak || true
    fi

    # 임시 최소 config (공식 packs 만 사용)
    cat > .semgrep/.semgrep.yml <<'YAML'
configs:
  - p/php
  - p/security-audit
  - p/secrets
exclude:
  - node_modules
  - vendor
  - .git
  - .github
paths:
  include:
    - "**/*.php"
YAML

- name: Run Semgrep (minimal config)
  run: |
    semgrep scan --config .semgrep/.semgrep.yml --json -o reports/semgrep.json || true

# (선택) 원복
- name: Restore original semgrep config (if backup exists)
  if: always()
  run: |
    if [ -f ".semgrep/.semgrep.yml.bak" ]; then
      mv .semgrep/.semgrep.yml.bak .semgrep/.semgrep.yml
    fi
