# .semgrep/.semgrep.yml
# ---------------------
# 怨듭떇 packs
configs:
  - p/ci
  - p/security-audit
  - p/secrets
  - p/php
  - p/javascript

# 濡쒖뺄 洹쒖튃??理쒖긽??rules ?꾨옒 ?ы븿
rules:
  - include: .semgrep/rules-xss.yml
  - include: .semgrep/rules-upload.yml
  - include: .semgrep/rules-sensitive.yml

# 湲곕낯 ?쒖쇅
exclude:
  - node_modules
  - vendor
  - .git
  - .github
  - dist
  - build
  - "**/*.min.js"
  - wp-includes/**
  - wp-admin/**

# 寃?ы븷 寃쎈줈
paths:
  include:
    - "src/**"
    - "**/*.php"

